name: Static Analysis

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  fmt:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Rustfmt
      run: cargo fmt -- --check

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Clippy
      run: cargo clippy --workspace --all-targets -- -D warnings
