name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:

  static_analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Run Rustfmt
      run: cargo fmt -- --check

    - name: Run Clippy
      run: cargo clippy --workspace --all-targets

  build_doc:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust Nightly
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: nightly
        override: true
        profile: minimal

    - name: Build rust doc
      run: cargo doc --all-features --no-deps
      env:
        RUSTDOCFLAGS: "--cfg docsrs"

  build:

    strategy:
      matrix:
        rust: [
            stable,
            nightly
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v1.3.0

    - name: Build
      run: cargo build --verbose

  test:

    strategy:
      matrix:
        rust: [
            stable,
            nightly
        ]

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v1.3.0

    - run: cargo test --verbose

  rpc-test:

    strategy:
      matrix:
        rust: [
            stable,
            nightly
        ]

    runs-on: ubuntu-latest

    services:
      bitcoin-core:
        image: ghcr.io/farcaster-project/containers/bitcoin-core
        env:
          NETWORK: regtest
          RPC_USER: ci
          RPC_PASS: ci
        ports:
          - 18443:18443

    steps:
    - uses: actions/checkout@v2

    - name: Install Rust ${{ matrix.rust }}
      uses: actions-rs/toolchain@v1.0.7
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal

    - uses: Swatinem/rust-cache@v1.3.0

    - name: Run regtest Bitcoin transactions
      run: cargo test --verbose --test transactions --features rpc -- --test-threads=1
      env:
        RPC_HOST: 127.0.0.1
        RPC_PORT: 18443
        RPC_USER: ci
        RPC_PASS: ci
